### ISSUE TITLE
Do not generate associated object if id is provided

### ISSUE THREAD

**Issue by sporto** [paulelliott/fabrication#250] opened 2015-05-26 04:48 UTC
Using sequel, I have a fabricator like:

```
Fabricator(:phone) do
	person
end
```

If I use this in the test like:

```
Fabricate(:phone, person_id: person.id)
```

A new person is created. I would expect fabricator to not create the associated object as I have already given the id.

**Comment by paulelliott** [comment] 2015-05-26 13:37
On your model, `person` and `person_id` are different fields. Your ORM ties them together although they can be set and read independently, which is why fabrication makes no assumptions about relationships between fields.

If you pass in `person` as you declared it in the fabricator you will see the expected behavior.

[duplicate of #249]

**Closed by paulelliott** 2015-05-26 13:37 UTC

**Comment by sporto** [comment] 2015-05-26 21:54
Thanks, it is clear that using person will give me the expected result.

What I am really after is a way to the Fabrication not to create a person if a person_id is already given.

**Comment by paulelliott** [comment] 2015-05-26 21:57
I provided a code snippet in my last comment on #249 that might make it work the way you're expecting.
