### ISSUE TITLE
before_validation callback in model is called twice

### ISSUE THREAD

**Issue by DmitryKK** [paulelliott/fabrication#273] opened 2016-03-10 19:57 UTC
Model:

```
class Company < ActiveRecord::Base

before_validation :confirm, on: :create

def confirm
  p "label 1"
  self.confirmed = true
end

```

Fabricator:

```
Fabricator(:company) do
  title "Test"

  after_validation { |company, _| company.confirmed = false; p "label 2" }
  before_save { |company, _| company.confirmed = false; p "label 3" }
end
```

```
company = Fabricate(:company)
"label 1"
"label 2"
"label 3"
"label 1"
=> #<CompanyPart:0x005617a35cc040>

company.confirmed 
=> true

```
But must be false!

I think there is double-check validation somewhere in the code of a gem

**Comment by paulelliott** [comment] 2016-03-11 13:53
This is a duplicate of #267

**Closed by paulelliott** 2016-03-11 13:53 UTC
